const SHARED_TCPA_CONSENT = `By clicking Submit, I agree to the <a href="/terms" target="_blank" rel="noopener noreferrer">Terms of use</a> and <a href="/privacy-policy" target="_blank" rel="noopener noreferrer">privacy policy</a> and authorize up to <a href="/marketing-partners" target="_blank" rel="noopener noreferrer">4 home improvement companies, their contractors and partners</a> to contact me with offers about home improvement products or services by telephone calls, emails, artificial voice, and pre-recorded/text messages, using an automated telephone technology, to the number and email I provided above, even if my number is a mobile number or is currently listed on any state, federal or corporate Do Not Call list. I understand that my consent here is not a condition of purchase of any goods or services. Message and data rates may apply. <a href="/privacy-policy" target="_blank" rel="noopener noreferrer">California Residents</a>. (or <a href="/do-not-sell-my-personal-information" target="_blank" rel="noopener noreferrer">Do Not Contact</a>).`;

export const funnelConfigs = {
  "roofing-v1pvcs": {
    heading: "Get a Free Roof Quote!",
    description: null,
    subtitle: "It only takes 30 seconds.",
    titleClassName: "funnel-title-black",
    showStepLogo: true,
    noCardBorder: true,
    thankYouHeading: "Great News — You Qualify!",
    thankYouServiceLabel: "roofing",
    steps: [
      {
        ...commonZipStep(),
        title: "See If Your Home Qualifies for a New Roof Installed At No Cost?",
        description: "Not all areas qualify — check your zip code",
        pageHeading: "",
        pageSubtitle: "",
        trustBadges: true,
      },
      {
        ...commonHomeTypeStep(),
        pageHeading: "",
        pageSubtitle: "",
        disqualifyOn: {
          values: ["Mobile Home", "Apartment"],
          title: "Thanks for your interest!",
          message: "This program is currently available only for single-family homes.",
        },
      },
      {
        key: "homeowner",
        title: "Do you own your home?",
        type: "options",
        options: ["Yes", "No"],
        pageHeading: "",
        pageSubtitle: "",
        disqualifyOn: {
          values: ["No"],
          title: "Thank you for checking!",
          message: "Our Roofing program is currently for homeowners only.",
        },
      },
      {
        key: "material",
        title: "What is your Roof Type?",
        type: "options",
        options: ["Asphalt", "Wood", "Tile/Clay", "Slate", "Metal", "Not Sure"],
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        key: "address",
        title: "What is the property address?",
        description: "We use this to check availability in your area",
        type: "input",
        placeholder: "Complete Address",
        hideLocationHint: true,
        pageHeading: "",
        pageSubtitle: "",
        showAnalyzing: true,
        nextLabel: "Check Availability",
      },
      {
        key: "name",
        title: "What's Your Name?",
        description: "",
        type: "input",
        fields: [
          { key: "firstName", placeholder: "First Name" },
          { key: "lastName", placeholder: "Last Name" },
        ],
        pageHeading: "",
        pageSubtitle: "",
        stepHeading: "Good News! We Found Someone In Your Area!",
      },
      {
        ...commonEmailStep(),
        title: "What's your email address?",
        description: "If we need to ask additional questions",
        nextLabel: "Next",
        pageHeading: "",
        pageSubtitle: "",
      },
      commonCreditStep(),
      {
        ...commonPhoneStep(),
        title: "Last Step: Enter your Phone Number to get your Results!",
        pageHeading: "",
        pageSubtitle: "",
        progressComplete: true,
        nextLabel: "👍 See My Results",
        nextButtonClassName: "next-btn-red",
      },
      { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
    ],
  },

  "windows-v1pvcs": {
    heading: "Get New Windows With No Upfront Cost!",
    description: null,
    subtitle: "It only takes 30 seconds.",
    titleClassName: "funnel-title-black",
    showStepLogo: true,
    noCardBorder: true,
    thankYouHeading: "Great News — You Qualify!",
    thankYouServiceLabel: "windows",
    steps: [
      {
        ...commonZipStep(),
        title: "Replace Your Windows For No Upfront Cost",
        description: "Not all areas qualify — check your zip code",
        pageHeading: "",
        pageSubtitle: "",
        trustBadges: true,
      },
      {
        key: "homeowner",
        title: "Do you own your home?",
        type: "options",
        options: ["Yes", "No"],
        pageHeading: "",
        pageSubtitle: "",
        disqualifyOn: {
          values: ["No"],
          title: "Thank you for checking!",
          message: "As of now, there aren't any offers available in your area.",
        },
      },
      {
        ...commonHomeTypeStep(),
        pageHeading: "",
        pageSubtitle: "",
        disqualifyOn: {
          values: ["Mobile Home", "Apartment"],
          title: "Thanks for your interest!",
          message: "This program is currently available only for single-family homes.",
        },
      },
      {
        key: "service",
        title: "Do Any Of Your Windows Currently Have Cracks, Chips, or Are Completely Broken?",
        description: "Many Home Insurance Companies Cover The Cost of a Broken or Cracked Window",
        type: "options",
        options: ["Yes", "No"],
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        key: "windowCount",
        title: "How many windows are you looking to replace?",
        type: "options",
        options: ["1-2", "3-5", "6-9", "10+"],
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        key: "address",
        title: "What is the property address?",
        description: "We use this to check availability in your area",
        type: "input",
        placeholder: "Complete Address",
        hideLocationHint: true,
        pageHeading: "",
        pageSubtitle: "",
        showAnalyzing: true,
        analyzingText: "Checking Availability...",
        nextLabel: "Check Availability",
      },
      {
        key: "name",
        title: "What's Your Name?",
        description: "",
        type: "input",
        fields: [
          { key: "firstName", placeholder: "First Name" },
          { key: "lastName", placeholder: "Last Name" },
        ],
        pageHeading: "",
        pageSubtitle: "",
        stepHeading: "Good News! We Found Someone In Your Area!",
      },
      {
        ...commonEmailStep(),
        banner: "YOU MAY QUALIFY FOR NO COST WINDOWS",
        title: "What's your email address?",
        description: "If we need to ask additional questions",
        nextLabel: "Send My Estimate →",
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        ...commonCreditStep(),
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        ...commonPhoneStep(),
        title: "Last Step: Enter your phone number to complete your request!",
        pageHeading: "Great News — You Qualify!",
        pageDescription: null,
        pageSubtitle: "",
        progressComplete: true,
        nextLabel: "👍 See My Results",
        nextButtonClassName: "next-btn-red",
      },
      { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
    ],
  },

  "solar-v1pvcs": {
  heading: "Get Solar For No Upfront Cost!",
  description: null,
  subtitle: "It only takes 30 seconds.",
  titleClassName: "funnel-title-black",
  showStepLogo: true,
  noCardBorder: true,
  thankYouHeading: "Great News — You Qualify!",
  thankYouServiceLabel: "solar",
  steps: [
    {
      ...commonZipStep(),
      title: "See If Your Home Qualifies For The {state}No Cost Solar Program!",
      description: "Not all areas qualify — check your zip code",
      pageHeading: "",
      pageSubtitle: "",
      nextLabel: "Check My Area →",
      trustBadges: true,
    },
    {
      key: "existingSolar",
      title: "Do you currently have solar panels installed?",
      description: "These programs are available for new installations only.",
      type: "options",
      defaultValue: "No",
      options: [
        { label: "No, not yet", value: "No" },
        { label: "Yes", value: "Yes" },
      ],
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["Yes"],
        redirectSlug: "roofing-v1pvcs",
        badge: "Solar Home Advantage",
        title: "Free Roof Check for Solar Homes",
        message: "Protect your solar investment with a complimentary roof inspection from our roofing specialists. We'll make sure your roof is ready for long-term solar performance.",
        bullets: [
          "Certified roofing pros familiar with solar installs",
          "Identify leaks, uplift, or wear before it spreads",
          "No-obligation guidance tailored to your home",
        ],
        ctaLabel: "Continue -->",
      },
    },
    {
      key: "homeowner",
      title: "Do you own your home?",
      description: "Homeowners may qualify for no cost installation",
      type: "options",
      options: ["Yes", "No"],
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["No"],
        title: "Thank you for checking!",
        message: "As of now, there aren't any offers available in your area.",
      },
    },
    {
      ...commonHomeTypeStep(),
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["Mobile Home", "Apartment"],
        title: "Thanks for your interest!",
        message: "This program is currently available only for single-family homes.",
      },
    },
    {
      key: "utilityCompany",
      title: "Who provides your electricity?",
      type: "select",
      placeholder: "Select utility company",
      searchPlaceholder: "Search utility company",
      dynamicOptionsFrom: "utilityLookup",
      options: [],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "electricBill",
      title: "About how much is your average monthly electric bill?",
      type: "range",
      min: 0,
      max: 500,
      step: 5,
      defaultValue: 150,
      prefix: "$",
      markers: [0, 100, 200, 300, 400, 500],
      maxLabel: "$500+",
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "address",
      title: "We Need To Analyze Your Roof For Shading",
      description: "We use satellite imagery to estimate your home's solar potential",
      hideLocationHint: true,
      type: "input",
      placeholder: "Enter property address",
      pageHeading: "",
      pageSubtitle: "",
      nextLabel: "Analyze My Roof",
      showAnalyzing: true,
    },
    {
      key: "name",
      title: "What's Your Name?",
      description: "",
      type: "input",
      fields: [
        { key: "firstName", placeholder: "First Name" },
        { key: "lastName", placeholder: "Last Name" },
      ],
      pageHeading: "",
      pageSubtitle: "",
      stepHeading: "Good News! Your Roof Gets Enough Sunlight!",
    },
    {
      ...commonEmailStep(),
      title: "What's your email address?",
      description: "If we need to ask additional questions",
      nextLabel: "Next",
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "creditRating",
      title: "What's your approximate credit score?",
      description: "This helps us determine which programs you qualify for",
      type: "options",
      options: [
        { label: "Excellent", value: "Excellent" },
        { label: "Good", value: "Good" },
        { label: "Fair", value: "Fair" },
        { label: "Poor", value: "Poor" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonPhoneStep(),
      title: "Last Step: Enter your Phone Number to get your Results!",
      pageHeading: "Great News — You Qualify!",
      pageDescription: null,
      pageSubtitle: "",
      progressComplete: true,
      nextLabel: "👍 See My Results",
      nextButtonClassName: "next-btn-red",
    },
    { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
  ],
},

  "turf-v1pvcs": {
  heading: "Get Artificial Turf Installed For No Upfront Cost!",
  description: null,
  subtitle: "It only takes 30 seconds.",
  titleClassName: "funnel-title-black",
  showStepLogo: true,
  noCardBorder: true,
  thankYouHeading: "Great News — You Qualify!",
  thankYouServiceLabel: "turf",
  steps: [
    {
      ...commonZipStep(),
      title: "Let's Make a Custom Turf Design For Your Home!",
      description: null,
      pageHeading: "",
      pageSubtitle: "",
      nextLabel: "Check My Area →",
      trustBadges: true,
    },
    {
      key: "homeowner",
      title: "Do you own your home?",
      description: null,
      type: "options",
      options: ["Yes", "No"],
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["No"],
        title: "Thank you for checking!",
        message: "As of now, there aren't any offers available in your area.",
      },
    },
    {
      ...commonHomeTypeStep(),
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["Mobile Home", "Apartment"],
        title: "Thanks for your interest!",
        message: "This program is currently available only for single-family homes.",
      },
    },
    {
      key: "turfLocation",
      title: "Where would you like artificial turf installed?",
      type: "options",
      options: [
        { label: "Front Yard", value: "Front Yard" },
        { label: "Back Yard", value: "Back Yard" },
        { label: "Both Front & Back", value: "Both Front & Back" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "address",
      title: "What is the property address?",
      description: "We use this to check the square footage of your yard.",
      hideLocationHint: true,
      type: "input",
      placeholder: "Enter property address",
      pageHeading: "",
      pageSubtitle: "",
      nextLabel: "Check Availability",
      showAnalyzing: true,
      analyzingText: "Analyzing Your Yard Square Footage...",
    },
    {
      key: "turfProjectType",
      title: "How do you plan to use your artificial turf?",
      type: "options",
      options: [
        { label: "🌿 A beautiful lawn year-round", value: "Lawn" },
        { label: "⛳ My own putting green", value: "Putting Green" },
        { label: "🌴 Both!", value: "Lawn and Putting Green" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "name",
      title: "What's your Name?",
      description: null,
      type: "input",
      fields: [
        { key: "firstName", placeholder: "First Name" },
        { key: "lastName", placeholder: "Last Name" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonEmailStep(),
      banner: "YOU MAY QUALIFY FOR NO COST ARTIFICIAL TURF",
      title: "Where should we send your mock up design?",
      description: "We'll email you personalized Turf options.",
      nextLabel: "Send My Design →",
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonCreditStep(),
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonPhoneStep(),
      title: "Last Step: Enter your phone number to complete your request!",
      pageHeading: "Great News — You Qualify!",
      pageDescription: null,
      pageSubtitle: "",
      progressComplete: true,
      nextLabel: "👍 See My Results",
      nextButtonClassName: "next-btn-red",
    },
    { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
  ],
},

  "home-security-v1pvcs": {
  heading: "",
  description: null,
  subtitle: "",
  titleClassName: "funnel-title-black",
  showStepLogo: true,
  noCardBorder: true,
  thankYouHeading: "Great News — You Qualify!",
  thankYouServiceLabel: "home security",
  steps: [
    {
      ...commonZipStep(),
      title: "See If Your Home Qualifies For a Home Security System!",
      description: "Check availability in your area",
      nextLabel: "Check My Area →",
      trustBadges: true,
    },
    {
      key: "homeowner",
      title: "Do you own your home?",
      type: "options",
      options: ["Yes", "No"],
      disqualifyOn: {
        values: ["No"],
        title: "Thank you for checking!",
        message: "As of now, there aren't any offers available in your area.",
      },
    },
    commonHomeTypeStep(),
    {
      key: "currentSecurity",
      title: "Do you currently have a home security system?",
      type: "options",
      layout: "stack",
      options: [
        { label: "No, I don't have one", value: "No" },
        { label: "Yes, but I want to upgrade", value: "Yes, looking to upgrade" },
        { label: "Yes, but I want to cancel", value: "Yes, looking to cancel" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "securityConcern",
      title: "What's your biggest security concern?",
      type: "options",
      layout: "stack",
      options: [
        { label: "🔒 Burglary / Break-ins", value: "Burglary" },
        { label: "🔥 Fire / Smoke", value: "Fire / Smoke" },
        { label: "💧 Flood / Water damage", value: "Flood / Water damage" },
        { label: "📷 Video surveillance", value: "Video surveillance" },
        { label: "👨‍👩‍👧 Overall family safety", value: "Overall family safety" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "address",
      title: "What's your property address?",
      description: null,
      hideLocationHint: true,
      type: "input",
      placeholder: "Enter property address",
      pageHeading: "",
      pageSubtitle: "",
      nextLabel: "Check Availability",
      showAnalyzing: true,
      analyzingText: "Checking Availability In Your Area",
    },
    {
      key: "name",
      title: "What's Your Name?",
      description: "",
      type: "input",
      fields: [
        { key: "firstName", placeholder: "First Name" },
        { key: "lastName", placeholder: "Last Name" },
      ],
      pageHeading: "",
      pageSubtitle: "",
      stepHeading: "Good News! We Found Someone In Your Area!",
    },
    { ...commonEmailStep(), title: "What's your email address?", description: "If we need to ask additional questions", pageHeading: "", pageSubtitle: "" },
    commonCreditStep(),
    {
      ...commonPhoneStep(),
      title: "Last Step: Enter your Phone Number to Get your Results!",
      pageHeading: "",
      pageDescription: null,
      pageSubtitle: "",
      progressComplete: true,
      nextLabel: "👍 See My Results",
      nextButtonClassName: "next-btn-red",
    },
    { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
  ],
},

  "bathroom-v1pvcs": {
  heading: "Get a Free Bathroom Remodel Quote!",
  description: null,
  subtitle: "It only takes 30 seconds.",
  titleClassName: "funnel-title-black",
  showStepLogo: true,
  noCardBorder: true,
  thankYouHeading: "Great News — You Qualify!",
  thankYouServiceLabel: "bathroom remodel",
  steps: [
    {
      ...commonZipStep(),
      title: "See if your home qualifies for a Free Bathroom Remodel Estimate",
      description: "Not all areas qualify — check your zip code",
      pageHeading: "",
      pageSubtitle: "",
      trustBadges: true,
    },
    {
      ...commonHomeTypeStep(),
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["Mobile Home", "Apartment"],
        title: "Thanks for your interest!",
        message: "This program is currently available only for single-family homes.",
      },
    },
    {
      key: "service",
      title: "What type of bathroom project are you considering?",
      type: "options",
      layout: "stack",
      pageHeading: "",
      pageSubtitle: "",
      options: [
        { label: "Walk-In Shower", value: "Walk-In Shower" },
        { label: "Bath to Shower Conversion", value: "Bath to Shower Conversion" },
        { label: "Full Bathroom Remodel", value: "Full Bathroom Remodel" },
        { label: "Bath/Shower Updates", value: "Bath/Shower Updates" },
        { label: "Walk-In Tub", value: "Walk-In Tub" },
        { label: "Not Sure / Need Recommendations", value: "Not Sure / Need Recommendations" },
      ],
    },
    {
      key: "homeowner",
      title: "Do you own the home?",
      type: "options",
      options: ["Yes", "No"],
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["No"],
        title: "Thank you for checking!",
        message: "As of now, there aren't any offers available in your area.",
      },
    },
    { ...commonCreditStep(), pageHeading: "", pageSubtitle: "" },
    {
      key: "address",
      title: "What is the property address for this bathroom project?",
      description: "We use this to check availability in your area",
      type: "input",
      placeholder: "Complete Address",
      hideLocationHint: true,
      pageHeading: "",
      pageSubtitle: "",
      showAnalyzing: true,
      nextLabel: "Check Availability",
    },
    {
      key: "name",
      title: "Who should we prepare this estimate for?",
      description: "So we can personalize your results",
      type: "input",
      fields: [
        { key: "firstName", placeholder: "First Name" },
        { key: "lastName", placeholder: "Last Name" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonEmailStep(),
      banner: "YOU MAY QUALIFY FOR A FREE BATHROOM REMODEL ESTIMATE",
      title: "Where should we send your results?",
      description: "We'll email your personalized quote",
      nextLabel: "Send My Estimate →",
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonPhoneStep(),
      title: "Last Step: Enter your Phone Number to get your Results!",
      pageHeading: "Great News — You Qualify!",
      pageDescription: null,
      pageSubtitle: "",
      progressComplete: true,
      nextLabel: "👍 See My Results",
      nextButtonClassName: "next-btn-red",
    },
    { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
  ],
},

  "gutters-v1pvcs": {
    heading: "Get a Free Gutter Quote!",
    description: null,
    subtitle: "It only takes 30 seconds.",
    titleClassName: "funnel-title-black",
    showStepLogo: true,
    noCardBorder: true,
    thankYouHeading: "Great News — You Qualify!",
    thankYouServiceLabel: "gutter",
    steps: [
      {
        ...commonZipStep(),
        title: "See if your home qualifies for a Free Gutter Inspection",
        description: "Not all areas qualify — check your zip code",
        pageHeading: "",
        pageSubtitle: "",
        trustBadges: true,
      },
      {
        ...commonHomeTypeStep(),
        pageHeading: "",
        pageSubtitle: "",
        disqualifyOn: {
          values: ["Mobile Home", "Apartment"],
          title: "Thanks for your interest!",
          message: "This program is currently available only for single-family homes.",
        },
      },
      {
        key: "service",
        title: "What type of gutter service do you need?",
        type: "options",
        options: ["Install", "Replace", "Repair"],
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        key: "homeowner",
        title: "Do you own the home?",
        type: "options",
        options: ["Yes", "No"],
        pageHeading: "",
        pageSubtitle: "",
        disqualifyOn: {
          values: ["No"],
          title: "Thank you for checking!",
          message: "As of now, there aren't any offers available in your area.",
        },
      },
      {
        key: "gutterType",
        title: "What type of gutters are you interested in?",
        type: "options",
        options: ["Seamless Metal", "Copper", "Galvanized", "PVC", "Wood", "Not Sure"],
        pageHeading: "",
        pageSubtitle: "",
      },
      { ...commonCreditStep(), pageHeading: "", pageSubtitle: "" },
      {
        key: "address",
        title: "What is the property address?",
        description: "We use this to check availability in your area",
        type: "input",
        placeholder: "Complete Address",
        hideLocationHint: true,
        pageHeading: "",
        pageSubtitle: "",
        showAnalyzing: true,
        nextLabel: "Check Availability",
      },
      {
        key: "name",
        title: "Who should we prepare this estimate for?",
        description: "So we can personalize your results",
        type: "input",
        fields: [
          { key: "firstName", placeholder: "First Name" },
          { key: "lastName", placeholder: "Last Name" },
        ],
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        ...commonEmailStep(),
        banner: "YOU MAY QUALIFY FOR A FREE GUTTER INSPECTION",
        title: "Where should we send your results?",
        description: "We'll email your personalized quote",
        nextLabel: "Send My Estimate →",
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        ...commonPhoneStep(),
        title: "Last Step: Enter your Phone Number to get your Results!",
        pageHeading: "Great News — You Qualify!",
        pageDescription: null,
        pageSubtitle: "",
        progressComplete: true,
        nextLabel: "👍 See My Results",
        nextButtonClassName: "next-btn-red",
      },
      { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
    ],
  },

  "hvac-v1pvcs": {
  heading: "",
  subtitle: "",
  titleClassName: "funnel-title-black",
  showStepLogo: true,
  noCardBorder: true,
  showCouponCode: true,
  steps: [
    {
      ...commonZipStep(),
      title: "See if Your Home Qualifies For a New A/C or Heater Unit For No Upfront Cost!",
      description: "Check availability in your area",
      nextLabel: "Check My Area →",
      trustBadges: true,
    },
    {
      key: "hvacSystem",
      title: "Which HVAC system do you need help with?",
      type: "options",
      layout: "stack",
      options: [
        { label: "Air Conditioner", value: "Air Conditioner" },
        { label: "Heating System", value: "Heating System" },
        { label: "Both", value: "Both" },
      ],
    },
    {
      key: "homeowner",
      title: "Do you own the home?",
      type: "options",
      options: ["Yes", "No"],
      disqualifyOn: {
        values: ["No"],
        title: "Thank you for checking!",
        message: "As of now, there aren't any offers available in your area.",
      },
    },
    commonHomeTypeStep(),
    {
      ...commonAddressStep("HVAC work"),
      title: "Lets check your Address for local discounts and promotions!",
      hideLocationHint: true,
      showAnalyzing: true,
      analyzingText: "Checking for Promotions In Your Area",
      nextLabel: "Check Promotions",
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "name",
      title: "What's Your Name?",
      description: "",
      type: "input",
      fields: [
        { key: "firstName", placeholder: "First Name" },
        { key: "lastName", placeholder: "Last Name" },
      ],
      pageHeading: "",
      pageSubtitle: "",
      stepHeading: "Good News! The No Cost A/C & Heater Replacement Program is Available In Your Area.",
    },
    { ...commonEmailStep(), title: "What's your email address?", description: "If we need to ask additional questions", pageHeading: "", pageSubtitle: "" },
    commonCreditStep(),
    {
      ...commonPhoneStep(),
      title: "Last Step: Enter your Phone Number to Claim your Coupon Code!",
      pageHeading: "Great News — You Qualify!",
      pageDescription: null,
      pageSubtitle: "",
      progressComplete: true,
      nextLabel: "👍 Claim My Code",
      nextButtonClassName: "next-btn-red",
    },
    { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
  ],
},

  "pest-control-v1pvcs": {
  heading: "Get a Free Pest Control Quote!",
  description: null,
  subtitle: "It only takes 30 seconds.",
  titleClassName: "funnel-title-black",
  showStepLogo: true,
  noCardBorder: true,
  thankYouHeading: "Great News — You Qualify!",
  thankYouServiceLabel: "pest control",
  steps: [
    {
      ...commonZipStep(),
      title: "See if Your Home Qualifies For a Free Pest Control Treatment!",
      description: "Check availability in your area",
      nextLabel: "Check My Area →",
      trustBadges: true,
    },
    {
      key: "pestType",
      title: "What pest problem are you dealing with?",
      type: "options",
      layout: "stack",
      options: [
        { label: "🐜 Ants", value: "Ants" },
        { label: "🪳 Roaches", value: "Roaches" },
        { label: "🐭 Rodents (Mice/Rats)", value: "Rodents" },
        { label: "🕷️ Spiders", value: "Spiders" },
        { label: "🐝 Wasps / Bees", value: "Wasps / Bees" },
        { label: "🦟 Mosquitoes", value: "Mosquitoes" },
        { label: "🐞 Termites", value: "Termites" },
        { label: "🐍 Other", value: "Other" },
      ],
    },
    {
      key: "pestLocation",
      title: "Have you spotted where they're coming from?",
      type: "options",
      layout: "stack",
      options: [
        { label: "Inside", value: "Inside" },
        { label: "Outside", value: "Outside" },
        { label: "Both", value: "Both" },
        { label: "No idea 😅", value: "No idea" },
      ],
    },
    {
      key: "pestSeverity",
      title: "How bad is it?",
      description: "This also helps contractors prioritize.",
      type: "options",
      layout: "stack",
      options: [
        { label: "Just started", value: "Just started" },
        { label: "Seeing them occasionally", value: "Seeing them occasionally" },
        { label: "Seeing them every day", value: "Seeing them every day" },
        { label: "It's become a major problem", value: "Major problem" },
      ],
    },
    {
      key: "homeowner",
      title: "Is this your home?",
      type: "options",
      options: [
        { label: "Yes, I own it", value: "Yes" },
        { label: "I rent it", value: "No" },
      ],
    },
    {
      key: "pestHistory",
      title: "Have you had pest control before?",
      description: "This tells the contractor what they're walking into.",
      type: "options",
      layout: "stack",
      options: [
        { label: "Never", value: "Never" },
        { label: "Yes, currently", value: "Yes, currently" },
        { label: "Yes, but I canceled", value: "Yes, but canceled" },
        { label: "I treated it myself", value: "Self-treated" },
      ],
    },
    commonHomeTypeStep(),
    {
      ...commonAddressStep("pest control service"),
      title: "What's your address?",
      hideLocationHint: true,
      showAnalyzing: true,
      analyzingText: "Checking Availability In Your Area",
      nextLabel: "Check Availability",
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "name",
      title: "What's Your Name?",
      description: "",
      type: "input",
      fields: [
        { key: "firstName", placeholder: "First Name" },
        { key: "lastName", placeholder: "Last Name" },
      ],
      pageHeading: "",
      pageSubtitle: "",
      stepHeading: "Good News! We Found Someone In Your Area!",
    },
    { ...commonEmailStep(), title: "What's your email address?", description: "Where should we send your recommendations?", pageHeading: "", pageSubtitle: "" },
    {
      ...commonPhoneStep(),
      title: "Last step! What's the best number for your local pest expert to reach you?",
      pageHeading: "",
      pageDescription: null,
      pageSubtitle: "",
      progressComplete: true,
      nextLabel: "👍 See My Results",
      nextButtonClassName: "next-btn-red",
    },
    { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
  ],
},

  "painting-v1pvcs": {
  heading: "Get a Free Painting Quote!",
  description: null,
  subtitle: "It only takes 30 seconds.",
  titleClassName: "funnel-title-black",
  showStepLogo: true,
  noCardBorder: true,
  thankYouHeading: "Great News — You Qualify!",
  thankYouServiceLabel: "painting",
  steps: [
    {
      ...commonZipStep(),
      title: "See if your home qualifies for a Free Painting Estimate",
      description: "Not all areas qualify — check your zip code",
      pageHeading: "",
      pageSubtitle: "",
      trustBadges: true,
    },
    {
      ...commonHomeTypeStep(),
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["Mobile Home", "Apartment"],
        title: "Thanks for your interest!",
        message: "This program is currently available only for single-family homes.",
      },
    },
    {
      key: "service",
      title: "What type of painting service do you need?",
      type: "options",
      layout: "stack",
      pageHeading: "",
      pageSubtitle: "",
      options: [
        "Exterior Painting - Trim/Shutters",
        "Exterior Painting - Whole House",
        "Interior Painting - 1 to 2 Rooms",
        "Interior Painting - 3+ Rooms",
        "Paint/Stain - Deck/Fence/Porch",
        "Paint/Stain Exterior Door",
        "Paint/Stain Interior Door",
        "Painting - Faux Finishes",
      ],
    },
    {
      key: "homeowner",
      title: "Do you own the home?",
      type: "options",
      options: ["Yes", "No"],
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["No"],
        title: "Thank you for checking!",
        message: "As of now, there aren't any offers available in your area.",
      },
    },
    { ...commonCreditStep(), pageHeading: "", pageSubtitle: "" },
    {
      key: "address",
      title: "What is the property address?",
      description: "We use this to check availability in your area",
      type: "input",
      placeholder: "Complete Address",
      hideLocationHint: true,
      pageHeading: "",
      pageSubtitle: "",
      showAnalyzing: true,
      nextLabel: "Check Availability",
    },
    {
      key: "name",
      title: "Who should we prepare this estimate for?",
      description: "So we can personalize your results",
      type: "input",
      fields: [
        { key: "firstName", placeholder: "First Name" },
        { key: "lastName", placeholder: "Last Name" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonEmailStep(),
      banner: "YOU MAY QUALIFY FOR A FREE PAINTING ESTIMATE",
      title: "Where should we send your results?",
      description: "We'll email your personalized quote",
      nextLabel: "Send My Estimate →",
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonPhoneStep(),
      title: "Last Step: Enter your Phone Number to get your Results!",
      pageHeading: "Great News — You Qualify!",
      pageDescription: null,
      pageSubtitle: "",
      progressComplete: true,
      nextLabel: "👍 See My Results",
      nextButtonClassName: "next-btn-red",
    },
    { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
  ],
},

  "siding-v1pvcs": {
  heading: "Get a Free Siding Quote!",
  description: null,
  subtitle: "It only takes 30 seconds.",
  titleClassName: "funnel-title-black",
  showStepLogo: true,
  noCardBorder: true,
  thankYouHeading: "Great News — You Qualify!",
  thankYouServiceLabel: "siding",
  steps: [
    {
      ...commonZipStep(),
      title: "See if your home qualifies for a Free Siding Estimate",
      description: "Not all areas qualify — check your zip code",
      pageHeading: "",
      pageSubtitle: "",
      trustBadges: true,
    },
    {
      ...commonHomeTypeStep(),
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["Mobile Home", "Apartment"],
        title: "Thanks for your interest!",
        message: "This program is currently available only for single-family homes.",
      },
    },
    {
      key: "service",
      title: "What type of siding service do you need?",
      type: "options",
      options: ["Install", "Replace", "Repair"],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      key: "homeowner",
      title: "Do you own the home?",
      type: "options",
      options: ["Yes", "No"],
      pageHeading: "",
      pageSubtitle: "",
      disqualifyOn: {
        values: ["No"],
        title: "Thank you for checking!",
        message: "As of now, there aren't any offers available in your area.",
      },
    },
    {
      key: "sidingMaterial",
      title: "Select the type of siding material you have:",
      type: "options",
      layout: "stack",
      pageHeading: "",
      pageSubtitle: "",
      options: [
        "Aluminum",
        "Brick or Stone",
        "Cement",
        "Metal",
        "Stucco",
        "Vinyl",
        "Wood",
      ],
    },
    { ...commonCreditStep(), pageHeading: "", pageSubtitle: "" },
    {
      key: "address",
      title: "What is the property address?",
      description: "We use this to check availability in your area",
      type: "input",
      placeholder: "Complete Address",
      hideLocationHint: true,
      pageHeading: "",
      pageSubtitle: "",
      showAnalyzing: true,
      nextLabel: "Check Availability",
    },
    {
      key: "name",
      title: "Who should we prepare this estimate for?",
      description: "So we can personalize your results",
      type: "input",
      fields: [
        { key: "firstName", placeholder: "First Name" },
        { key: "lastName", placeholder: "Last Name" },
      ],
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonEmailStep(),
      banner: "YOU MAY QUALIFY FOR A FREE SIDING ESTIMATE",
      title: "Where should we send your results?",
      description: "We'll email your personalized quote",
      nextLabel: "Send My Estimate →",
      pageHeading: "",
      pageSubtitle: "",
    },
    {
      ...commonPhoneStep(),
      title: "Last Step: Enter your Phone Number to get your Results!",
      pageHeading: "Great News — You Qualify!",
      pageDescription: null,
      pageSubtitle: "",
      progressComplete: true,
      nextLabel: "👍 See My Results",
      nextButtonClassName: "next-btn-red",
    },
    { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
  ],
},

  "walk-in-tubs-v1pvcs": {
    heading: "Get a Free Walk-In Tub Quote!",
    description: null,
    subtitle: "It only takes 30 seconds.",
    titleClassName: "funnel-title-black",
    showStepLogo: true,
    noCardBorder: true,
    thankYouHeading: "Great News — You Qualify!",
    thankYouServiceLabel: "walk-in tub",
    steps: [
      {
        ...commonZipStep(),
        title: "See if your home qualifies for a Free Walk-In Tub Estimate",
        description: "Not all areas qualify — check your zip code",
        pageHeading: "",
        pageSubtitle: "",
        trustBadges: true,
      },
      {
        ...commonHomeTypeStep(),
        pageHeading: "",
        pageSubtitle: "",
        disqualifyOn: {
          values: ["Mobile Home", "Apartment"],
          title: "Thanks for your interest!",
          message: "This program is currently available only for single-family homes.",
        },
      },
      {
        key: "homeowner",
        title: "Do you own the home?",
        type: "options",
        options: ["Yes", "No"],
        pageHeading: "",
        pageSubtitle: "",
        disqualifyOn: {
          values: ["No"],
          title: "Thank you for checking!",
          message: "As of now, there aren't any offers available in your area.",
        },
      },
      { ...commonCreditStep(), pageHeading: "", pageSubtitle: "" },
      {
        key: "address",
        title: "What is the property address?",
        description: "We use this to check availability in your area",
        type: "input",
        placeholder: "Complete Address",
        hideLocationHint: true,
        pageHeading: "",
        pageSubtitle: "",
        showAnalyzing: true,
        nextLabel: "Check Availability",
      },
      {
        key: "name",
        title: "Who should we prepare this estimate for?",
        description: "So we can personalize your results",
        type: "input",
        fields: [
          { key: "firstName", placeholder: "First Name" },
          { key: "lastName", placeholder: "Last Name" },
        ],
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        ...commonEmailStep(),
        banner: "YOU MAY QUALIFY FOR A FREE WALK-IN TUB ESTIMATE",
        title: "Where should we send your results?",
        description: "We'll email your personalized quote",
        nextLabel: "Send My Estimate →",
        pageHeading: "",
        pageSubtitle: "",
      },
      {
        ...commonPhoneStep(),
        title: "Last Step: Enter your Phone Number to get your Results!",
        pageHeading: "Great News — You Qualify!",
        pageDescription: null,
        pageSubtitle: "",
        progressComplete: true,
        nextLabel: "👍 See My Results",
        nextButtonClassName: "next-btn-red",
      },
      { ...commonVerificationStep(), pageHeading: "", pageSubtitle: "" },
    ],
  },
};

function commonZipStep() {
  return {
    key: "zip",
    title: "What is your zip code?",
    type: "input",
    placeholder: "Enter your zip code",
    nextLabel: "Check My Area →",
  };
}

function commonAddressStep(target) {
  return {
    key: "address",
    title: `Type below the home address where you want the ${target} to be installed`,
    type: "input",
    placeholder: "123 Main St, Springfield, IL 62701",
  };
}

function commonEmailStep() {
  return {
    key: "email",
    title: "What email address can our contractors reach you at?",
    type: "input",
    placeholder: "name@example.com",
  };
}

function commonFirstNameStep() {
  return {
    key: "firstName",
    title: "What’s your first name?",
    type: "input",
    placeholder: "John",
  };
}

function commonLastNameStep() {
  return {
    key: "lastName",
    title: "What’s your last name?",
    type: "input",
    placeholder: "Doe",
  };
}

function commonPhoneStep() {
  return {
    key: "phone",
    title: "What phone number should contractors call?",
    type: "input",
    placeholder: "(555) 555-5555",
    hasLinkedConsent: true,
  };
}

function commonVerificationStep() {
  return {
    key: "verificationCode",
    title: "Enter the Verification code that we have sent to your phone",
    type: "input",
    placeholder: "------",
  };
}

function commonCreditStep() {
  return {
    key: "creditRating",
    title: "What's your approximate credit score?",
    description: "This helps us determine which programs you qualify for",
    type: "options",
    options: ["Excellent", "Good", "Fair", "Poor"],
  };
}

function commonHomeTypeStep() {
  return {
    key: "propertyType",
    title: "What Type Of Home Do You Live In?",
    type: "image-options",
    subtitle: "Select Your Response Below",
    options: [
      { label: "Single Family Home", icon: "🏠", image: "/single-family-home.webp" },
      { label: "Mobile Home", icon: "🚐", image: "/services/mobile-home.webp" },
      { label: "Apartment", icon: "🏢", image: "/services/apartment.webp" },
    ],
  };
}